--CLI_ACCESOS_CLIENTE
INSERT INTO public.CLI_ACCESOS_CLIENTE(ID_ACCESO, CODIGO, DESCRIPCION) VALUES (1, 'A', 'acceso beto');
INSERT INTO public.CLI_ACCESOS_CLIENTE(ID_ACCESO, CODIGO, DESCRIPCION) VALUES (2, 'A', 'acceso victor');
INSERT INTO public.CLI_ACCESOS_CLIENTE(ID_ACCESO, CODIGO, DESCRIPCION) VALUES (3, 'A', 'acceso mariano');
INSERT INTO public.CLI_ACCESOS_CLIENTE(ID_ACCESO, CODIGO, DESCRIPCION) VALUES (4, 'A', 'acceso ivan');
INSERT INTO public.CLI_ACCESOS_CLIENTE(ID_ACCESO, CODIGO, DESCRIPCION) VALUES (5, 'A', 'acceso hernan');

--CLI_CONTACTO
INSERT INTO public.CLI_CONTACTO(ID_CONTACTO, BARRIO, CODIGO_POSTAL, DOMICILIO, LOCALIDAD, PROVINCIA, NOMBRE_CONTACTO, TEL_FIJO, TEL_CELULAR) VALUES (1, 'Agronomía', 'C1417', 'Larrea 142', 'CABA', 1, 'Beto', '42223344' , '1142223344');
INSERT INTO public.CLI_CONTACTO(ID_CONTACTO, BARRIO, CODIGO_POSTAL, DOMICILIO, LOCALIDAD, PROVINCIA, NOMBRE_CONTACTO, TEL_FIJO, TEL_CELULAR) VALUES (2, 'Almagro', 'C1172', 'Tucuman 651 ', 'CABA', 1, 'Victor', '41116633' , '1141116633');
INSERT INTO public.CLI_CONTACTO(ID_CONTACTO, BARRIO, CODIGO_POSTAL, DOMICILIO, LOCALIDAD, PROVINCIA, NOMBRE_CONTACTO, TEL_FIJO, TEL_CELULAR) VALUES (3, 'Balvanera', 'C1020', 'Piedras 56', 'CABA', 1, 'Mariano', '47770088' , '1147770088');
INSERT INTO public.CLI_CONTACTO(ID_CONTACTO, BARRIO, CODIGO_POSTAL, DOMICILIO, LOCALIDAD, PROVINCIA, NOMBRE_CONTACTO, TEL_FIJO, TEL_CELULAR) VALUES (4, 'Boedo', 'C1218', 'Paso 981', 'CABA', 1, 'Ivan', '45559911' , '1145559911');
INSERT INTO public.CLI_CONTACTO(ID_CONTACTO, BARRIO, CODIGO_POSTAL, DOMICILIO, LOCALIDAD, PROVINCIA, NOMBRE_CONTACTO, TEL_FIJO, TEL_CELULAR) VALUES (5, 'Barracas', 'C1066', 'Las Heras 1000', 'CABA', 1, 'Hernan', '41234567' , '1141234567');

--CLI_IDENTIFICACION
INSERT INTO public.CLI_IDENTIFICACION(ID_IDENTIFICACION, NUMERO_ID, TIPO_ID) VALUES (1, '33123222', 'DNI');
INSERT INTO public.CLI_IDENTIFICACION(ID_IDENTIFICACION, NUMERO_ID, TIPO_ID) VALUES (2, '31635612', 'DNI');
INSERT INTO public.CLI_IDENTIFICACION(ID_IDENTIFICACION, NUMERO_ID, TIPO_ID) VALUES (3, '30212356', 'DNI');
INSERT INTO public.CLI_IDENTIFICACION(ID_IDENTIFICACION, NUMERO_ID, TIPO_ID) VALUES (4, '33573137', 'DNI');
INSERT INTO public.CLI_IDENTIFICACION(ID_IDENTIFICACION, NUMERO_ID, TIPO_ID) VALUES (5, '34723453', 'DNI');


--CLI_CLIENTE
INSERT INTO public.CLI_CLIENTE(ID_CLIENTE, TIPO_CLIENTE, BLOQUEADO, EMAIL, FECHA_ALTA_PASSWORD, FECHA_NAC, FECHA_REGISTRO, GENERO, NACIONALIDAD, INTENTOS_FALLIDOS_LOGIN, PASSWORD, NOMBRE, APELLIDO, REQUIERE_CAMBIO_PASSWORD, USERNAME, ID_ACCESOS) VALUES (1, 'PROFESOR', false, 'avacotest@gmail.com', NULL, NULL, '2020-06-20 00:0:0.000', 'M', 'Argentino', 0, '$2a$10$9EmXkvYDoxA/rwi2.uxOue/I2Z2.6fzIubnhKnjFEQvCESbfzuqZm', 'Alberto', 'Gonzales', false, 'agonzalez', 1);
INSERT INTO public.CLI_CLIENTE(ID_CLIENTE, TIPO_CLIENTE, BLOQUEADO, EMAIL, FECHA_ALTA_PASSWORD, FECHA_NAC, FECHA_REGISTRO, GENERO, NACIONALIDAD, INTENTOS_FALLIDOS_LOGIN, PASSWORD, NOMBRE, APELLIDO, REQUIERE_CAMBIO_PASSWORD, USERNAME, ID_ACCESOS) VALUES (2, 'PROFESOR',false, 'avacotest1@gmail.com', NULL, NULL, '2020-06-20 00:0:0.000', 'M', 'Argentino', 0, '$2a$10$9EmXkvYDoxA/rwi2.uxOue/I2Z2.6fzIubnhKnjFEQvCESbfzuqZm', 'Victor', 'Cabas', false, 'vcabas', 2);
INSERT INTO public.CLI_CLIENTE(ID_CLIENTE, TIPO_CLIENTE, BLOQUEADO, EMAIL, FECHA_ALTA_PASSWORD, FECHA_NAC, FECHA_REGISTRO, GENERO, NACIONALIDAD, INTENTOS_FALLIDOS_LOGIN, PASSWORD, NOMBRE, APELLIDO, REQUIERE_CAMBIO_PASSWORD, USERNAME, ID_ACCESOS) VALUES (3, 'ALUMNO', false, 'avacotest2@gmail.com', NULL, NULL, '2020-06-20 00:0:0.000', 'M', 'Argentino', 0, '$2a$10$9EmXkvYDoxA/rwi2.uxOue/I2Z2.6fzIubnhKnjFEQvCESbfzuqZm', 'Mariano', 'Petrakovsky', false, 'mpetra', 3);
INSERT INTO public.CLI_CLIENTE(ID_CLIENTE, TIPO_CLIENTE, BLOQUEADO, EMAIL, FECHA_ALTA_PASSWORD, FECHA_NAC, FECHA_REGISTRO, GENERO, NACIONALIDAD, INTENTOS_FALLIDOS_LOGIN, PASSWORD, NOMBRE, APELLIDO, REQUIERE_CAMBIO_PASSWORD, USERNAME, ID_ACCESOS) VALUES (4, 'ALUMNO', false, 'avacotest3@gmail.com', NULL, NULL, '2020-06-20 00:0:0.000', 'M', 'Argentino', 0, '$2a$10$9EmXkvYDoxA/rwi2.uxOue/I2Z2.6fzIubnhKnjFEQvCESbfzuqZm', 'Ivan', 'Imoff', false, 'iimoff', 4);
INSERT INTO public.CLI_CLIENTE(ID_CLIENTE, TIPO_CLIENTE, BLOQUEADO, EMAIL, FECHA_ALTA_PASSWORD, FECHA_NAC, FECHA_REGISTRO, GENERO, NACIONALIDAD, INTENTOS_FALLIDOS_LOGIN, PASSWORD, NOMBRE, APELLIDO, REQUIERE_CAMBIO_PASSWORD, USERNAME, ID_ACCESOS) VALUES (5, 'ALUMNO', false, 'avacotest4@gmail.com', NULL, NULL, '2020-06-20 00:0:0.000', 'M', 'Argentino', 0, '$2a$10$9EmXkvYDoxA/rwi2.uxOue/I2Z2.6fzIubnhKnjFEQvCESbfzuqZm', 'Hernan', 'Gomez Molins', false, 'hgomez', 5);

